---
title: "about these notes"
description: |
  what's the sausage and how is it made?
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


I am David Passmore.

#### how these notes are rendered

These NOTES originate in Pittsburgh, Pennsylvania, where I have lived since 2020. I was a professor at Penn State for 41 years and in higher education for 51 years. Additional details about my background, experiences, and accomplishments <a href="https://davidpassmore.net" title="Passmore bio" target="_blank">are available elsewhere</a>.

I write these NOTES in <a href="https://rmarkdown.rstudio.com/" target="_blank" title="RMarkdown">RMarkdown</a> code in <a href="https://www.rstudio.com/" target="_blank" title="RStudio">RStudio</a> using blogging tools provided in the <a href="https://www.r-project.org/" target="_blank" title="R">R programming</a> package titled <a href="https://cran.r-project.org/web/packages/distill/index.html" target="_blank" title="distill package">`distill`</a>. I render the blog in <a href="https://en.wikipedia.org/wiki/HTML" target="_blank" title="html in Wikipedia">html</a> from the RMarkdown code. Then, I push the html to <a href="https://github.com/davidpassmore" target="_blank" title="Passmore GitHub account">my GitHub account</a>, from which it is served publicly through the <a href="https://en.wikipedia.org/wiki/Domain_name" target="_blank" title="domain name in Wikipedia">domain name</a>, `davidpassmore.github.io/blog/`. Cookies and other tracking tools are not implemented on this blog site.

#### what's here?

These NOTES cover a wide variety of topics that reflect the range of ideas, learnings, and challenges that I encounter daily as I sit with my computers at a table in front of the large windows that look over trees, birds, and daily neighborhood activities from our 4th floor condo in the Shadyside neighborhood of Pittsburgh. 

#### how I engage

I live my days as a retired person. I rise at 4:00 am daily. Early rising is not my attempt to follow some monastic way. No, see it as a quiet time, an opportunity to organize and prepare, and a chance to have a few accomplishments before the rest of the world starts moving. I meet over my cup of morning coffee with long-time friends on Zoom from 6:30 to 7:30 am on Mondays through Saturdays. 

The remainder of my time on most days is spent on projects selected from too many to do. Sometimes I video conference with friends and collaborators across the world. I am in a sleep research study that requires that I get five hours of sleep per night, so I am asleep by 11:00 pm. Between rising and finally going to sleep, I do the purchasing, shopping, bill-paying, cooking, laundering, medicating, cleaning, banking, and so forth.

#### contacts with me

Friends, this blog is a gated community.

Send email to me using the email address: `dlp AT davidpassmore.net`. I take *iMsgs* and *SMS messages* at `dlp@psu.edu`. My *Twitter* handle is `@DLPPassmore`, where I am available publicly. I also run *Slack* teams for my former students and my family. In these student and family teams, I typically am available instantly. I have placeholder accounts in many social media apps, I do not do the *FaceBook*s or the *LinkedIn*s for anything meaningful. So, not much of me is available on those apps. The telephone? Nah. I almost never pick up, expect for family or for calls from close associates. Calling me without leaving a message results in a blocked calling number.^[Please note: my car warranty is as I like it; my grandchildren do not require me to bail them out of jail; the Internal Revenue Service is not trying to reach me urgently.] I *do* use Instagram, but I am deeply hidden and accessible by family only. I live in a secure building, so, instead of making direct threats to me face-to-face, post any expressions of unhappiness and ill-will to me via email or Twitter, where I will work ideas into my life flow. 

Vr,


