---
title: "snow"
description: |
  Back in the day, when it really snowed, and no one worked on Sunday....written in 2005
preview: snowsquall.jpg
author:
  - name: David L. Passmore
    url: https://davidpassmore.net
    orcid_id: 0000-0001-9307-5164
    affiliation: Distinguished Professor, Emeritus, Penn State; Academic Visitor, University of Pittsburgh
date: 2005-01-22
categories:
  - memories
  - weather
  - Niagara Falls
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

It is 17 degrees F outside. The wind will pick up, and the snow will drift. 

*Rocky*, some version, is on the TNT network right now, and Rocky is kissing Adrianne for the first time. There's the heat, eh? But, on to *snow*.

Snow. Snow is not to watch. Snow is to be in the midst of. I grew up in Niagara Falls, New York. Snow, in all its variations, is familiar.

Once, when I was about 15 years old, almost 30 inches of snow fell. In the early evening after supper, I called a girl, who was my buddy who lived down the street, on the phone. We agreed to dress in quadruple layers, complete with scarves, several wool hats, and two or three gloves. Our parents thought we were crazy. We met under the street light at the end of the street, and we were off.

The storm was thick. Snow was still coming down in big, feathery flakes, accumulating on top of the inches already on the ground. The wind blew in off the Niagara River and molded the snow into long, undulating drifts across the field next to my house. The lights from the ever-working chemical factories--*Hooker Electrochemical*, *Alox*, among others--and the *Kimberly Clark* paper mill made the large flakes of snow settling over the open field glow like crystal.

The field of snow was untouched. It was a perfect, white blanket. My friend and I started out through the snow. For her, the snow seemed to be waist high. I was much taller, but still it was tough slogging for me. We had agreed days before that we would run through the next heavy snow just to determine what it would feel like.

We took off at a run. Well, a run like running in a pool of water. I plowed the way; my friend followed. As we picked up speed, the exhilaration of the run kicked in. My friend was no jock, so she was winded. As we neared the fence of the *Hooker Electrochemical* plant, the harmonics of the drifts increased. A foot of snow. Then, four feet of snow! At once we were running freely, only in the next moment to hit some drift like smashing into a wall of pillows.

We hit one immense drift, and we both fell. It was a soft tumble down the side of a drift and into a trough that contained nothing but yellow/brown tall grass made brittle by the extreme cold. We both sat there panting between two great drifts.

Oh, I know what you are thinking, but I never thought of my friend in other than brother-sister terms. Her mom was like my mom. She might have thought differently at some point. She did invite me to a special sophomore school dance. Maybe she just needed a date. At any rate, I never had any special feelings for her. However, my girlfriend at the time was pretty unhappy that I accompanied my friend to the dance. But, hey, I did agree to go months before.

As we sat there, my friend said to me, "Your girlfriend is very pretty."

"Yeh, I know."

"What do you like about her?," she asked.

"Well, she is nice. She has large brown eyes and is beautiful, don't you think?"

She agreed. 

I said, "And, she likes me, too."

"But, why?," my friend resting in the snow asked. It wasn't a question that was meant to tease me. It was a serious question.

I confess, I couldn't figure out why. I didn't answer. It was a mystery to me, and it still is. I knew what I felt. I couldn't fathom what my beautiful girlfriend felt. To this day, I only know what I feel. I can't imagine what others see.

We sat there on the ground quietly for what must have been five minutes. We weren't cold yet--too many layers of clothes. Spotlights from the factories broke through the air, at once putting the spaces between the drifts into sharp contrast and, then, in the next instant diffusing light over the surging, scudding seas of white flakes.

It was a Sunday night. The world used to stop on Sundays, not like now when we have 24-hour news, the presence of all-night convenience stores, and the Internet. No, the city was quiet on Sunday nights in 1962, and the industrial plants were, too. You could hear the wind blow over the drifting snow. 

A swish like sand moving on a windswept beach told the story of the the flakes of snow moving here and there and piling into greater mounds only to shift again to regroup, to combine into new mounds and shapes. It was difficult to believe that on this same spot boys played baseball in the summer and people walked through these very reedy grasses, to be frightened to death here and there by the explosion of a frightened pheasant. Winter created a new and different world, indeed.

Then, without any discussion, we both rose and walked slowly back through our almost covered tracks over the 100 yards or so to civilization. I walked my friend to her home, where we stripped off all but the last layer and my friend's mom, Mabel, made us steaming hot cocoa with marshmallows. 

Mabel was quite a card. As always, she had her bobby-pinned hair in a a wrap and wore a flowered housecoat. She looked for all the world like the wife in the Andy Capp comic strip. Mabel was a Canadian citizen, and she held irreverent opinions about the United States that perhaps were the the seeds of my first critical political thoughts.

I carried my extra layers of clothes home in my hands. I was quite tired, although it was still early night. I threw my snow- and ice-covered clothes in the corner, where they puddled on the floor to my mother's dismay, said good night to my parents, and went to my room. 

I remember looking out my bedroom window toward the factory lights on the horizon. The snow still fell, and it continued throughout the night. No school the next day. I distinctly remember wondering about the future before I went to bed that night. What would I be like when I was old -- say, 40 or 50 years old? Haha! Here I am 57^[Now, as I update this posting for a modern blog, 74] years old. Not much different, eh?

Snow. It arrives, at times, light and free. Other times, heavy and wet. Sometimes the flakes are big and feathery. At other times, the word, *flake*, does not describe the pinpoints that drive into your cheeks as you struggle to walk into the wind. Occasionally, snow is delivered with a howl, almost parallel to the ground. Yet, certain snows waft down calmly, riding back and forth on light breezes. Snow can melt on warm blacktop driveways. It can stick like cotton candy to surfaces. It also can pile like dump trucks dropped it off by mistake on your sidewalk. Like a sweet, soft painting, or like a frightening roller coaster ride. All various. Every snow new.

So, this is the snow I see. The snow accumulates here in Pennsylvania today. We are not done yet. The weather people say it will continue through the evening.

Oh, by the way, the movie just ended. Rocky won the fight, of course, and he still loves Adrianne. She just ran into the ring and kissed that big lug with the blood on his face and the sweat dripping off him. It is a mystery, isn't it?

## Reuse {.appendix}

Text and figures are licensed under Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Source code is available at https://github.com/davidpassmore/blog, unless otherwise noted. The figures that have been reused from other sources don't fall under this license and can be recognized by a note in their caption: "Figure from ...".

## Comments/Corrections {.appendix}

To make comments about this posting or to suggest changes or corrections, send email to [David Passmore](dlp@davidpassmore.net), send a direct message on Twitter @DLPPassmore, or send an IMsg or SMS to dlp@psu.edu.

